/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    AppNavBar: typeof import('./src/components/AppNavBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NamePopUp: typeof import('./src/components/NamePopUp.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
